name: build

on:
  push:
    branches: e2e-refactor

  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.19]
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - name: Build CLI
        run: make build-linux-amd64
      - name: Start Distribution
        run:  |
          docker stop oras-distro-e2e
          docker run -dp --rm 5000:5000 --name oras-distro-e2e ghcr.io/oras-project/registry:v0.0.3-alpha
      - name: Run Unit Tests
        run: make test
      - name: Stop Distribution
        run: |
          docker stop oras-distro-e2e
      - name: Check Version
        run: bin/linux/amd64/oras version
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v3
